let finnhubKey = "__FINNHUB_KEY__"

struct Marque: Identifiable {
    let symbol: String
    let nom: String
    let domaine: String
    var id: String { symbol }
}

let contacts = ["Camille Martin", "Lucas Bernard", "Emma Dubois", "Hugo Petit", "Léa Moreau", "Théo Laurent"]

let marques: [Marque] = [
    Marque(symbol: "AAPL", nom: "Apple", domaine: "apple.com"),
    Marque(symbol: "MSFT", nom: "Microsoft", domaine: "microsoft.com"),
    Marque(symbol: "GOOGL", nom: "Google", domaine: "google.com"),
    Marque(symbol: "AMZN", nom: "Amazon", domaine: "amazon.com"),
    Marque(symbol: "META", nom: "Meta", domaine: "meta.com"),
    Marque(symbol: "TSLA", nom: "Tesla", domaine: "tesla.com"),
    Marque(symbol: "NVDA", nom: "Nvidia", domaine: "nvidia.com"),
    Marque(symbol: "NFLX", nom: "Netflix", domaine: "netflix.com"),
    Marque(symbol: "DIS", nom: "Disney", domaine: "disney.com"),
    Marque(symbol: "NKE", nom: "Nike", domaine: "nike.com"),
    Marque(symbol: "KO", nom: "Coca-Cola", domaine: "coca-cola.com"),
    Marque(symbol: "PEP", nom: "PepsiCo", domaine: "pepsico.com"),
    Marque(symbol: "MCD", nom: "McDonald's", domaine: "mcdonalds.com"),
    Marque(symbol: "SBUX", nom: "Starbucks", domaine: "starbucks.com"),
    Marque(symbol: "CMG", nom: "Chipotle", domaine: "chipotle.com"),
    Marque(symbol: "DPZ", nom: "Domino's Pizza", domaine: "dominos.com"),
    Marque(symbol: "V", nom: "Visa", domaine: "visa.com"),
    Marque(symbol: "MA", nom: "Mastercard", domaine: "mastercard.com"),
    Marque(symbol: "PYPL", nom: "PayPal", domaine: "paypal.com"),
    Marque(symbol: "JPM", nom: "JPMorgan", domaine: "jpmorganchase.com"),
    Marque(symbol: "BAC", nom: "Bank of America", domaine: "bankofamerica.com"),
    Marque(symbol: "GS", nom: "Goldman Sachs", domaine: "goldmansachs.com"),
    Marque(symbol: "WMT", nom: "Walmart", domaine: "walmart.com"),
    Marque(symbol: "COST", nom: "Costco", domaine: "costco.com"),
    Marque(symbol: "TGT", nom: "Target", domaine: "target.com"),
    Marque(symbol: "HD", nom: "Home Depot", domaine: "homedepot.com"),
    Marque(symbol: "ADBE", nom: "Adobe", domaine: "adobe.com"),
    Marque(symbol: "CRM", nom: "Salesforce", domaine: "salesforce.com"),
    Marque(symbol: "ORCL", nom: "Oracle", domaine: "oracle.com"),
    Marque(symbol: "INTC", nom: "Intel", domaine: "intel.com"),
    Marque(symbol: "AMD", nom: "AMD", domaine: "amd.com"),
    Marque(symbol: "QCOM", nom: "Qualcomm", domaine: "qualcomm.com"),
    Marque(symbol: "IBM", nom: "IBM", domaine: "ibm.com"),
    Marque(symbol: "CSCO", nom: "Cisco", domaine: "cisco.com"),
    Marque(symbol: "UBER", nom: "Uber", domaine: "uber.com"),
    Marque(symbol: "LYFT", nom: "Lyft", domaine: "lyft.com"),
    Marque(symbol: "DASH", nom: "DoorDash", domaine: "doordash.com"),
    Marque(symbol: "ABNB", nom: "Airbnb", domaine: "airbnb.com"),
    Marque(symbol: "SPOT", nom: "Spotify", domaine: "spotify.com"),
    Marque(symbol: "SHOP", nom: "Shopify", domaine: "shopify.com"),
    Marque(symbol: "SNAP", nom: "Snapchat", domaine: "snap.com"),
    Marque(symbol: "PINS", nom: "Pinterest", domaine: "pinterest.com"),
    Marque(symbol: "ZM", nom: "Zoom", domaine: "zoom.us"),
    Marque(symbol: "RBLX", nom: "Roblox", domaine: "roblox.com"),
    Marque(symbol: "EA", nom: "Electronic Arts", domaine: "ea.com"),
    Marque(symbol: "TTWO", nom: "Take-Two", domaine: "take2games.com"),
    Marque(symbol: "SONY", nom: "Sony", domaine: "sony.com"),
    Marque(symbol: "TM", nom: "Toyota", domaine: "toyota.com"),
    Marque(symbol: "F", nom: "Ford", domaine: "ford.com"),
    Marque(symbol: "GM", nom: "General Motors", domaine: "gm.com"),
    Marque(symbol: "BA", nom: "Boeing", domaine: "boeing.com"),
    Marque(symbol: "GE", nom: "General Electric", domaine: "ge.com"),
    Marque(symbol: "XOM", nom: "ExxonMobil", domaine: "exxonmobil.com"),
    Marque(symbol: "CVX", nom: "Chevron", domaine: "chevron.com"),
    Marque(symbol: "TTE", nom: "TotalEnergies", domaine: "totalenergies.com"),
    Marque(symbol: "PFE", nom: "Pfizer", domaine: "pfizer.com"),
    Marque(symbol: "JNJ", nom: "Johnson & Johnson", domaine: "jnj.com"),
    Marque(symbol: "LLY", nom: "Eli Lilly", domaine: "lilly.com"),
    Marque(symbol: "SNY", nom: "Sanofi", domaine: "sanofi.com"),
    Marque(symbol: "T", nom: "AT&T", domaine: "att.com"),
    Marque(symbol: "VZ", nom: "Verizon", domaine: "verizon.com"),
    Marque(symbol: "PG", nom: "Procter & Gamble", domaine: "pg.com"),
    Marque(symbol: "LULU", nom: "Lululemon", domaine: "lululemon.com"),
    Marque(symbol: "LVMUY", nom: "LVMH", domaine: "lvmh.com"),
    Marque(symbol: "HESAY", nom: "Hermès", domaine: "hermes.com"),
    Marque(symbol: "COIN", nom: "Coinbase", domaine: "coinbase.com"),
    Marque(symbol: "HOOD", nom: "Robinhood", domaine: "robinhood.com"),
    Marque(symbol: "PLTR", nom: "Palantir", domaine: "palantir.com"),
    Marque(symbol: "BABA", nom: "Alibaba", domaine: "alibabagroup.com"),
    Marque(symbol: "NIO", nom: "NIO", domaine: "nio.com")
]